name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  npm:
    strategy:
      matrix:
        node: [12.x, 15.x]
        os: [ubuntu-latest]
        vue: [2, 3]
      fail-fast: false
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm -v
      - run: node .github/test.js npm ${{ matrix.vue }} simple
  
  yarn:
    strategy:
      matrix:
        node: [12.x, 14.x]
        os: [ubuntu-latest]
        vue: [2, 3]
        yarn: [latest, berry]
        type: [simple, workspace]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node .github/test.js yarn ${{ matrix.vue }} ${{ matrix.type }} ${{ matrix.yarn }}
  
  pnpm:
    strategy:
      matrix:
        node: [12.x, 14.x]
        os: [ubuntu-latest]
        vue: [2, 3]
        type: [simple, workspace]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g pnpm
      - run: pnpm -v
      - run: node .github/test.js pnpm ${{ matrix.vue }} ${{ matrix.type }}
