name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node: [12.x, 14.x, 15.x]
        os: [ubuntu-latest]
        vue: ["vue@2 @vue/composition-api", "vue@3"]
        
    runs-on: ${{ matrix.os }}
    steps:
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: mkdir test && cd test
    - run: npm -v
    - run: npm init -y
    - run: npm i ${{ matrix.vue }}
    - run: npm i vue-demi
    - run: cat node_modules/vue-demi/lib/index.cjs.js
